spring.cache.type=redis

grading.queue.enabled=true
grading.queue.name=grading-jobs
grading.worker.enabled=true
grading.worker.concurrency=4
grading.worker.poll-timeout=5s

# prod and local host versions are in local and prod properties respectively
